<?php
/**
 * This file is part of application with Laminas MVC framework
 * 
 * Template: 'user/display-users/index'
 * 
 * @var Laminas\View\Renderer\PhpRenderer $this
 * 
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/application
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
// Set title
$headTitle = 'Alle Nutzer dieser Webanwendung anzeigen';
$this->headTitle($headTitle);
// Set meta description
$metaDescription = 'Alle registrierten Nutzer werden nach der Kontonummer aufgelistet.';
// Set meta keywords
$metaKeywords = 'Nutzer, Webanwendung, anzeigen';
$this->headMeta()->appendName('description', $metaDescription)
        ->appendName('keywords', $metaKeywords)
        ->appendName('DC.title', $headTitle);
?>
<main>
    <header id="main-header">
        <h1>
            Alle registrierten Nutzer
        </h1>
    </header>
<?php
    foreach ($this->users as $user) {
?>
    <section>
        <h2>
            Konto-<?= $user->getId() . "\n" ?>
        </h2>
        <ul>
            <li>
                <?= $this->escapeHtml($user->getAlias()) . "\n" ?>
            </li>
            <li>
                <?= $this->escapeHtml($user->getEmail()) . "\n" ?>
            </li>
            <li>
            <?php
                if (0 === $user->getStatus()) {
            ?>
                gesperrt
            <?php
                } else {
            ?>
                aktiv
            <?php
                }
            ?>
            </li>
        </ul>
        <ul class="link-buttons-nav">
            <li>
                <a class="link-button-primary"  href="<?= $this->url('user-detail', ['id' => $user->getId()]); ?>">
                    Anzeigen
                </a>
            </li>
            <li>
                <a class="link-button-success" href="<?= $this->url('edit-user', ['id' => $user->getId()]) ?>">                    
                    Bearbeiten
                </a>
            </li>
            <li>
                <a class="link-button-danger" href="<?= $this->url('delete-user', ['id' => $user->getId()]) ?>">                    
                    Löschen
                </a>
            </li>
        </ul>
    </section>
    <hr>
<?php
    }
?>
</main>
