<?php

/**
 * This file is part of application with Laminas MVC framework
 * 
 * This is the default layout (layout/layout) template of this web application.
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @link       https://github.com/nik-web/application
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<?= $this->doctype() ?>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle()->setAutoEscape(false) . PHP_EOL ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?= $this->headMeta() . PHP_EOL ?>
    </head>
    <body>
        <?= $this->content ?>     
    </body>
    <footer id="site-footer">
            <?= $this->copyright_notice()->render() . PHP_EOL; ?>
    </footer>
</html>