<?php

/**
 * This file is part of application with Laminas MVC framework
 * 
 * This file is a partial view script for the app icons.
 * 
 * Template: partial/meta/app-icons
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @link       https://github.com/nik-web/application
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
?>

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/app-icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/app-icons/favicon-16x16.png">
<link rel="manifest" href="/app-icons/site.webmanifest">
<link rel="mask-icon" href="/app-icons/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">